---
title: 无忘当时
author: 金吉
date: '2014-08-29'
slug: ''
categories:
  - '2014'
tags: []
---

###  中国农业大学峰云社

[2014年人文科考队](https://v.youku.com/v_show/id_XODAxMzE5ODY4.html?spm=a2h0c.8166622.PhoneSokuUgc_1.dtitle).



#### 支教篇

-  “当一艘船沉入海底，当一个人成了谜。你不知道，他们为何离去，那声再见竟是他最后一句……”

今天是回来后的第一个晚上，不知不觉脑中总是出现《后会无期》的歌词，便想到有两首歌虽然不在歌词本中，但却是队伍中每个人都喜欢的，是我这一路上听的最多的被大家哼唱的。我也曾想过为什么我们十六个不同风格的人都喜欢这两首歌，最后我认为大概是歌词和我们太相像，“我曾经跨过山和大海，也曾穿越人山人海，我曾经拥有着一切，转眼都飘散如烟。我曾经失落失望失掉所有方向，直到看见平凡才是唯一的答案。”

清楚的记得大一时的“百团大战”，各个社团都想尽办法展示自己，希望有更多的同学加入。当时我就来到过峰云社的展位，还问了一些社员：“你们真的会去西藏吗?”想来当时回答我的必定是去过科考的老队员，她们激动地向我说：“当然去过，你看，这是今年去西藏的照片.”但是我上个学期却没有加入峰云社，已经填好的报名表又被我丢入垃圾桶，心里想万一这要是个坑呢。后来院里的雨洁、宛蔚、包孝客都加入了峰云社，看着他们一天天在社里都很快乐，并且有一天晚训我也跟在队伍后面跑步，最后阿杰很热情的邀请我一起做伸展活动，当时心里就很感动，心想下学期一定要加入峰云社。

再一次开学已是大一下学期了，经历过一个学期大学生活的我心中很明确自己想要什么，于是便加入了峰云社，清楚的记得那天在办公室值班的是邱瑜，所以我加入了办公室和岩队。最初只是参加晚训和大家一起跑跑步，直到宣讲会出现，让我在社里有了转折。

宣讲会上，雪山和科考都令我着迷，但是相比雪山，西藏这片神秘的土地更加吸引我，再加上彩泉孩子们的一张张笑脸，使我毫不犹豫的填写了科考的报名表，开始了人生的新旅程。

- “怎么会忘了，那些一言为定，与不言说的默契，很高兴遇见你，在惊天动地的岁月里......”

为了入选科考队，每名队员都付出了很多，我们一起早训晚训，准备试讲，应战笔试，就这样，最后的名单确定了，记得当时我是在一觉醒来后发现的入选通知，当时整个人就清醒了，内心的激动无法言表。因为我知道，这个夏天，我们15个人，注定会在一起，注定会不平凡!


- “Oh lights go down, in the moment we are lost and found, I just want to be by your side, if these wings could fly.”

这几天每天早上醒来，都是被太真实的梦惊醒，不断的梦见我还在西藏，我还在科考，我还在你们身边。听起来是不是太过矫情，连我自己也相信，当初那个不喜欢晚训，不喜欢开会，不喜欢被约束的刺头，竟然迟迟走不出科考带给她的回忆。记得小智曾经说过科考就是能让你在不经意想起的时候，独自傻笑的那个。那么我们能傻笑或是暗自流泪多久呢？大概是一辈子了吧。

 
- “回头望望来时的路，经幡飞扬星辰闪亮”

所有的美丽只因遇见你。去拉萨时乘坐的T27次列车是我人生中坐火车时间最长的一次了，去樟木时坐了15个小时的大巴也是我人生中第一次坐那么长时间的大巴车，这两段旅程我都十分开心，是它们让我看到了至今为止见过的最壮阔的风景。窗外，荒漠，油菜花田，岩石，雪山，牛羊，蓝天，云海，经幡，山谷，江河，以及那条绵延向远方的路。我曾经说过，“我们这四个月来所跑的每一步，都将带我们去西藏。”西藏真的很远啊，可是我们来了，因为我们曾经坚持过，坚持过让汗水浸湿衣衫也不放弃。

 
- “回到彩色故乡，牵着手聊聊梦想。”

彩泉之于我，有道不完的离殇。其实我是一个不喜欢小孩子的人，因为我觉得他们很闹很吵，但当我第一天和他们正式见面的时候，我就改变了。我拿着本子和笔让他们把名字写下来给我，他们一个个的都很愿意，也很羞涩，写完就跑开了，我的心中有说不出的感动。给孩子们讲课，但是认真听的人很少，能记住的人则更少，要是以前，我心中肯定会不满，埋怨他们不懂得好好读书的重要性。但是来到这里，看到了真实的他们，我有些心酸。想想他们几十个孩子，平日里根本得不到亲人的关心和照顾，小孩子的衣服哥哥姐姐帮忙洗，大一点的孩子既要洗自己的衣服，又帮弟弟妹妹洗衣服。他们只能学会互相关爱。平时的娱乐活动也很少，小孩子们就在一起打打闹闹，大孩子则多数在电视房看各种视频，根本没有机会去感受外面的世界，他们失去的太多，得到的太少，我又有什么理由去怪他们呢？

支教的几天里，有很多时候我是很苦恼的。因为我觉得我根本改变不了什么。讲过的知识会被忘记，你来了，你走了，最后还是老样子。时常羡慕莎莎，因为他总是有快乐的理由，总是被一群孩子围住。莎莎今年已经是第四年参加科考了，西藏这片土地对他早已不是神秘，我想支持他来到这里的一定是这群彩泉的孩子，可是又为什么呢？萍姐跟我说她义无反顾的来第二次也是为了孩子，我不理解，我们究竟能带给他们什么？

转眼就到了最后一天-----游园会。这一天的彩泉热闹无比，各种小游戏让大孩子小孩子都欢聚到了一起，兑奖处的零食、小玩具也是孩子们眼中的珍宝。我和刘琦一起负责抢收种地这个游戏，有很多孩子参与，虽然我们都忙得很累，但心中却是真的开心。唱歌，跳舞，演话剧，项目按照计划一样样的进行着，我的心情却越来越沉重，因为我知道，别离就快要到了。

游园会结束后，小孩子们的情绪也明显低落了一些，三五个的拉扯在和自己更亲密的哥哥姐姐身边，说着什么，或者什么都不说，就是静静的坐着。我的旁边也坐着次央，我把提前买好的文具拿了出来，送到她手上，告诉她她很聪明，要努力学习，要考一所好的大学。

她说：“老师，会的。”


- “我要牢牢记住你的脸，我会珍惜你给的思念，这些日子在我心中永远都不会改变。我不能答应你，我是否会再回来，不回头，不回头的走下去。”

从来没觉得我会哭，但是这首歌被我们16个人清唱出来的时候，我的眼泪不由自主的从脸颊划过，我真的觉得这每一句歌词，都是为今天的我们而写的，那么的贴切，那么的深情。不回头，不回头的走下去。再见了彩泉，再见了孩子们，我相信，有一天我们会再见的。

#### 科考篇

- “你在身旁，点滴里溢满暖阳。心念远方，肩并肩走过路长。”

樟木这个小镇，像是天堂一样的地方，置身楼顶，空中的云仿佛伸手可触。下雨之前起了大雾，会让你有种置身仙境的感觉。整个小镇由上到下只有一条马路，路的两侧建起各式风格的三、四层高彩色小楼，远远望去，就像是童话里的被森林围绕的城堡。调研的日子虽然辛苦，但是大家聚在一起的时间也更多了，每天五元的早餐钱被精确到半根油条，1元两个的陕西馒头花卷别有风味，八人三菜一汤的蓉城小吃总是觉得应该是四个人的标配，木板气垫加睡袋睡起来总是格外香甜。其中穿插的蚂蝗路，立新村，火锅鱼，尼泊尔饭，中尼友谊大桥，罗林商店等等故事我就不细说了，相信大家都会记得。

 
- “很高兴遇见你，在惊天动地的青春里。”

一直憧憬期待的散伙饭终于降临了，也可以说我期待的本不是饭，而是酒。从来都觉得酒就是一种既难喝又邪恶的东西，所以我从来不喝酒，也就不知道自己的酒量究竟是多少。心想正好趁着散伙饭检验一下。喝了一杯又一杯，越喝越觉得自己内心的情感被放大了，而且明显走不稳路了，酒精的效果发挥了，可是我的意识还是清醒的，我清楚的知道现在正发生着什么。跟大家都说了很多话，这些话我都记得，我没有醉，你们要相信。

 

 
后记：后来琦琦告诉我，顾老大在火车经过唐古拉山口的时候还是高反了，只是怕大家担心没有说出来，我真的很惭愧之前一直不知道，在这里说声抱歉。写完这篇感想，我的科考后时代也就结束了，科考之于我也画上了一个句号。我不敢说这个句号画得是否圆满，我只想说我画过了。人生有许许多多的岁月，会遇到许许多多个人，但是再也不会重复这四个月，再也不会有这16个人。时光在不停飞逝，路还在脚下延伸，唯有记忆停留在过去，等待着想要回忆它的我们。

 
- 金吉拉姆，

- 14.8.23 晚  23:24

 

#### 吐槽篇

01：“宛蔚，白水煮面条和大馒头真的那么好吃吗？看你吃得我都馋了。”

02：益菱：“女神来讲个笑话。”   我：“你看我像不像笑话？”（外加鄙视的眼神）

03：管子：“我要成为队里顶天立地的人！”   我：“放心吧，有我在还不用你顶。”  管子：“。。。。。。。”

04：我：“肉老师帮我照相！”  肉松：“两块钱一张啊。”  我：“your sister.”

06:偲偲：“天使”  ,我：“谁是你天使啊，哼。。”

07:“炸毛体温多少啊？” 毛毛：“37.9，，，”（外加委屈无辜的小表情）

08：我：“倒数第一名，快来跟着第一名啊”  大琦：“好叻。”

09：我：“老大，种地累不累啊？”    老大： “老大已经累完了”    益菱：“你们够了。”

10：我：“蛋蛋你好有钱啊，居然去过那么多地方。”   蛋蛋：“都是我爸带我去的”  我：“这个拼爹的时代。。。。

11：我：“领导，下午有事来你寝室待会啊。”   领导：“啊，随便待。金吉你自己玩啊，我再睡一会儿。”

12：我：“萍姐我要吃曲奇饼干”，  “萍姐我要喝酸奶”， 萍姐，，萍姐？？

13：“嬷嬷，今天可以不练神功吗？上次练完以后腿一直疼。“

14：杨瀚：”天使，我要吃奥利奥，黑白配，巧克力 ，还有可爱多。天使你看着办吧。“

15：“圈哥，立新村鸡的病你会治吗？”    圈哥：“孩子你想多了。”

16：“莎莎，帮我拍一个美美的照片。”   莎莎：“好。”



>《让子弹飞》里出了很多名言，“虾仁猪心” 算是其中之一。以前没有体会，现在在搬运各处散落的自己“年轻”时写的文，体会到了，少壮不努力，老大徒伤悲啊......

