---
title: A Question During Judo Testing and Some Thoughts
author: Kimki
date: '2021-07-29'
slug: a-question-during-judo-testing
categories:
  - '2021'
tags: []
---

- "When your parents first learned that you were practicing **judo**, what was their reaction? You know, since judo is a martial art and you may hurt yourself during practice. They might feel worried ".  This is one of the questions on the judo belt test yesterday. 

Ryan said his parents might have little concerns but they are fine with him doing it.  
Taylor said her mom is very supportive, sometimes she even asks Taylor to do some throws on her.   
"My parents were really happy when they knew I was practicing judo, because I used to do more dangerous sports, such as mountain bike downhill, skydiving, bungee,etc". They all laughed after hearing my answer.   

I am grateful that my parents have given me enough freedom since I was a kid.They are great parents, always willing to dedicate whatever they have to me. However, growing up, I do remember one thing deeply. That was an afternoon when I was in the third grade of elementary school. Although, my home was around 30 minutes' walk from school, my parents rarely come to pick me up from school. That day after school, assuming no one was coming to pick me up, I went to a store in my elementary school and bought a milk ice cream bar with the only fifty cents(0.5￥) I had. That milk ice cream bar was my favorite ice cream, even now, I can still recall how it tastes like. I was very happy, eating while approaching to the school gate. Soon after, I saw my dad standing outside the gate. Apparently, he didn't look happy since that's already more than 15 minutes after school. I didn't care so much as walked to him. However, I was petrified when he suddenly grabbed my ice cream bar and threw it away. What happened afterwards was not important, but this incident has always been a shadow of my childhood. After that, I seldom bought ice cream bar after school. Now I am living alone, sometimes I buy 7 pints of ice cream and finish it in one week(I eat tons of ice cream during finals).

Personally, I think most of Chinese parents are extremely generous, they pay everything for their kids, not only raise them to 18 years old, but also help them with their college tuition, housing down payment, buying cars, babysitting, etc. But they are also very dictatorial sometimes. I was a little in fear of my dad before I went to college, of course I am not now. Now, I feel my parents are more in "fear" of me. They all try their best to follow my ideas, my decisions.

I never mentioned it to my father, since I am old enough and this won't happen again(I surely will if he is going to have another kid, but that's impossible). Just like a line from my favorite Korean drama [Reply 1988](https://en.wikipedia.org/wiki/Reply_1988):

> Dads don’t automatically become dads the moment you’re born either. It’s my first time being a dad too. So, I’d like it if you could go easy on me.

Fate made us father and daughter, and I am willing to be more tolerant with you.









