---
title: 昨日
author: 金吉
date: '2015-11-29'
slug: ''
categories:
  - '2015'
tags: []
---


暑期的规矩，向来是要有一篇写在后面的感想的，回来已经很久了，迟迟没有动笔，不是因为不想写，实则不敢。今日动笔，翻阅自己的小日记本，半回忆半照抄，来完成走之前的最后一件事，内容长，文笔差，诸君若能看完，在下提前感谢了。

忘了是在路上的哪一天，也忘了是哪个人曾经说过，“我们啊，离开后就再难聚齐了。” “短途团”，在车协也是一支特殊的队伍，走过之后再回首，我只想说：“路程虽短，回忆尤长，情亦深。”

一切都起源于三教的那场宣讲会，听闻七月的青海湖边，油菜花田美得让人心醉，便下决心用一种不一样的方式去欣赏。五一三天的赤壁拉练，让我改变了以往对车协的印象，上坡，雨骑，山路，碎石，大桌饭，大保健，经历过的事，陪伴在身边的人，让我在五一归来后就提交了千字自述，主题只有一个：“我想和你们，一起骑车看风景”。努力着，拉练，晚训，跑步和爬坡的体测，互评，一切都那么顺其自然的发生着，一支由13个人组成的短途团正式成立了。最初的我们都不很了解，酒神给起的好名字，君心哥哥推荐的队歌，团购清单，身体调查，队服投票，路线制作，拆车托车……一件件事情做好了，我们彼此也越来越熟悉了，出发的日子也渐渐靠近了。

2015年7月17日的早上，北京下着小雨，东校区，在很多朋友们的送行下，“西海佳遇”出发了。一个人坐火车多是孤独的，一群人坐火车，那真是快乐的。一路上吃不完的水果，玩不完的游戏。狼人杀，我喜欢当上帝，从普通版本，扩展到最后的双重身份最强大脑版，我只想说，下次玩，一定要先票死伟佳；你比我猜，嘉铭真乃体育神人，晓蕾姐和我配合学霸版本简直默契，贤德经验丰富；谁是卧底，一群男生掉节操，大电影，小电影，有什么区别现在我也没弄清楚；整容和美容，苦茶和绿茶，现在一点点回忆起这些时光，还是能一个人坐在电脑前笑出声来，我想，这大概就是最纯粹的快乐了吧。

当然，困难也是存在的，30多小时的硬座毕竟不好忍受，为了能让部分队友睡得舒服一点，有些队友们就一夜未睡，等到早上之前休息的人都醒来，才躺在防潮垫上开始休息，队友情谊，从一开始就很深了。

嘉峪关是一个普通的小城，一座城楼命名的城市。第一晚就住在一家普通的旅馆里面，我们找了一家很不错的餐馆吃饭，吃到了暑期路上的第一顿大盘鸡，大盘鸡和牛肉拉面这两种食物真是贯穿了暑期餐桌。还有“927”车队带领我们的夜骑，暑期第一次骑上自己的车，体验落日的美，欢腾的大合跳。

敦煌之旅算是暑期前期最让大家感动的了，犹记桃园客栈的美丽温馨，杏儿香甜，真的很羡慕店主一家人，能够在那么美丽的地方，用一颗淡雅从容的心经营生活。鸣沙山月牙泉，虽然是景区，但是跟我以往经历的那些景区都不同，大概是沙漠太广阔，广阔到任凭我们肆意奔跑，夕阳西下，暮色醉人，脱掉鞋袜，双脚踩在沙里的温暖，以及一起拍下的一张张照片，都会记得很久很久吧。


##### 千里之行，始于此，甘肃-嘉峪关

7月21日，第一次上路了。路很平，风却很大。上午走了60，最后当了不到一个小时的前骑，才知道前骑的压力真的很大，也很累，没想到最后这一个小时成为了我暑期唯一的一段前骑时光。下午骑到90左右的时候就感觉自己要掉队了，频繁的换着音响的歌曲，一遍遍鼓励自己，才没有掉。一路上都在跟佳佳吐槽前骑骑得慢，后来不知怎么的，后面的清奕货架掉了，然后前面的人停下来休息，我和陈世鼎去打前站，这是一个40公里的逆风的前站，也是我第一次打前站，最后我们住在15/人的农舍里，吃了214元的晚餐，我也学会了找旅馆，找饭店，以后便成为了前站女王（应该没有女生打前站比我多了，laugh cry）。 

7月22日，我毛遂自荐，有机会当了大旗。一路上缓下居多，因此并不觉得累，下午我们很早就到了临泽。不过因为种种原因，我们没能领略丹霞地貌的壮美，也就继而发生了暑期路上第一次气氛沉重的队会。其实现在回想起来已经不记得争吵什么的了，只是觉得队友之间能够敞开心扉，有什么不爽的都说出来，是一个很好的传统，以后也会延续的。

7月23日，今日一路缓上，骑得真是很累。由于前两天骑车的座位高度不合适，我的右脚开始出现麻木的状况，这让我一个动医出身的人十分恐慌，说实话，对骑车已经心生恐惧了，可是骑行才刚刚开始，也不能怂啊，于是拼命的坚持着，跟紧前骑们。下午的时候，我们遇见了最美的向日葵花田，遇见了一群有梦想的老者，遇见了一条水花激扬的激流，也体验到了最后15公里的绝望。晚饭是君心哥哥的美女同学请的，西北人民的热情豪放让我们知道了什么叫一桌三道菜，三道菜一桌！

7月24日，开始了暑期路上最艰难两天中的第一天。上午30公里缓上后，开始了两个妙峰山距离的爬坡。太阳很大，坡也很长，暑期路上第一次自由爬坡开始了。一开始我还很有自信的跟在袁帅后面，5公里过后直接看不见他的背影了。接着就被嘉铭、红祯、伟佳超过了，一点点的又被佳佳、君心哥哥超，心中真是悲凉啊，好在第一次休息的时候又追上了前面的人。最后到达山顶的时候真是激动啊，没有荫凉可以休息，就躺在车子驮包下的点点荫凉里，阳光晒在身上，整个人都很暖。人齐之后，开始了很爽的一段下坡，几百米的海拔几分钟就降下来了。

这天下午对我的暑期应该意义重大，是一个转折。是的，我摔车了，至今仍清楚的记得，在一个很长的扁担坡上，我们骑的是单列，我在第三名的位置上。用暑假很火的一个电影来比喻，我的前面有两个破风手，他们带的有些快，缓下的时速在30-40km/h之间。然后我看到嘉铭作了一个减速的手式，然后经验不足的我就按了前后刹，感觉自己的车在剧烈摇摆中又受到了其他外力，然后整个人就飞出去了，躺在黑色的路面上。后来那些不够坚强的部分本是不想写了，只是回来之后翻照片，发现还有我摔车时的记录，心里真的是很有感触。记得佳佳第一个跑过来抱着我，记得大家一起拦的车，记得嘉铭陪我去的祁连县医院，记得贤德和鼎哥在坎坷中牵了几十里路的车，记得剩下的人要走的一段没有修好，又漆黑一片的路，记得打前站的君心哥哥在路边冻得发抖，伟佳也是在独自一人去找餐馆……其实在暑期结束之后我也反思过，我其实很在意这次摔车，我的新车受伤了，人也受伤了，也没有完成一千多公里的骑行。途中的地方很偏僻，伤口四五天没有换过药，都化脓后又粘在皮肤上了。在西宁中医院第一次换药时，痛得我已经感觉到自己快要休克了，眼泪不自主的流。我曾经因此而烦恼，我在纠结，为什么自己会摔车。可是在我们最后全部分开的时候，我又释怀了。今年暑期路上，每条队伍都有人摔车，在骑行过程中，摔车也是最常经历的事情了。我是一个不太优秀的队医，给你们的药总是不能及时解决病症，这一次，既然总会有人摔车，那不如那个人就是我好了。

7月25日，和他一起坐车提前来到默勒镇，找到了一家小旅馆，碰巧对外经贸的蚂蚁车协也在这里。听你们说了爬上4120的不易与欢乐，晚上再见你们，你们明显都黑了好多。晚上的队会，现在想起来心都酸酸的，也许我真是一个泪点太低的人。听到贤德说要走之后，我的心里就很难过了。其实我当初报名短途团，有一半的原因是因为贤德，我觉得他是一个性格非常和善的人，所以也一定会是一个好队长，当他的队员肯定也很开心，其实最终也是。和贤德在一起聊天，在一起玩，他总是会逗我们笑，作为队长也自己默默做了很多我们不知道的事，上路的几天里，也感觉他总是有心事。我还记得我当时的发言，“唯梦想与真心不可辜负”。其他的队友也都很支持贤德自己的决定，我本以为事情就这样结束的时候，有一件令人沉默的消息公布了。君心哥哥也因为要出国的事情，必须得提前走了。脆弱玻璃心的我，一想到自己还受伤无法骑车，内心已经是崩溃的了，我都想要买张票直接返回北京了。后来发生的一切证明，人没有那么脆弱，事情一点点做，总会解决的。我的后暑期时代开始了。

##### 两个人的暑期路

7月26号，把驮包里重要的东西留下，其他的都寄回了北京。纠结了很久，最终决定把车留下来，尽管中间还有一个小插曲，我的前轮丢在了一辆大巴车上，只好把贤德的前轮装在了我的车上。一个人去了刚察，找到了旅馆，饭店。那是队伍少人之后的第一天，晚上开会的时候大家没有我想象的沉默，大家都很开心，超煜做着队长总结，大家的情绪都很好，最后我们还跟贤德和君心哥哥视了频。或许是我这个人总是那么悲观，遇到事情总是喜欢逃避，是你们教会了我，生命中没有什么事值得长久的悲伤，明天又是新的一天。

7月27号，两个人骑在队伍后面，整个队伍也开始了环青海湖的第一天。路上的风景真的很美，青海湖时远时近，最后在一个偶然的路口，我们来到了湖边，我尝到了它咸咸的味道，也领略了它的壮美，那不就是在宣讲会上，我曾向往的吗？更何况当时还没有想到过，身边会多一个陪伴的人，顿时觉得很幸福。120公里的路程不长，但对于有伤在身的我还是一个不小的挑战。最后我们来到了暑期路上最贵的黑马河乡，这里的稀饭要5块钱一碗，西红柿鸡蛋炒饭要20块；体验了当蔬菜的感觉，因为我们11个人住在一个大棚里；晚上吃到了用羊粪生火煮出来的大锅面，没有什么味道，而且煮得过分的熟，但是我们很开心的全部吃完了。

7月28号，早上起来看了极美的日出。
上午大家一起去了传说中的天空之镜---茶卡盐湖。现在回想起来，风景应该也算美丽，脚下都是白花花的盐粒，一座座灰白色的巨大的盐雕静静的供游人欣赏。只是我太疲惫了，匆匆进去，匆匆出来，只觉得太阳好大好晒，通往盐湖的车又多又吵。回黑马河乡的车上实在觉得难受，两个病号在一起自感无法继续陪大家走完剩下的环湖路程，于是选择提前坐车去西宁等大家。站在路边等了好久，最终和一个刚高考完的学弟一起拼车到了西宁，下车时已经是晚上8点多了。

7月29号，早上起来后，去青海中医院换药，下午把火车站及托车，其他人旅馆的问题解决了。晚上一起去西宁最繁华的地方吃饭，逛街，听两个非常默契的街头歌手唱歌。后来也带大家一起去听了，还推荐了对面kFC两元一个的甜筒。

7月30号，下午终于和大家又汇合了，十分开心。他的病也重了，自己一个人去了医院。

7月31号，上午大家一起去塔尔寺游览，因为之前对藏传寺庙有接触，因此我并没有去。下去一起去火车站把爱车送回北京，在西宁站前照下了最后的带车合影。晚上散伙饭终于来了，先去了一家小火锅店，大家都吃到了七八分饱，后来觉得没有喝酒，不开心，于是又走了很远，来到了西宁市的烧烤一条街。等待位置的过程中，大家把队旗拿了出来，依次，一面面的签好自己的名字。吃饭，重要的不是饭，喝酒，重要的也不是酒，是每个人，是每一段故事，是有我们的那些故事。我们的暑期也就算最终谢幕了，我的故事也讲完了。[西海真的有佳遇。](https://www.youtube.com/watch?v=VS5_OUEnl4E&t=1s)





